### PR TITLE
V3.3.3

### PR DESCRIPTION
**Pull request by renich**

### CODE REVIEW

**Review by abique — APPROVED** [review]

**Comment by abique** [comment]
your pull request has conflicts.

**Comment by renich** [comment]
Huh? How so? I don't see them. 
image

**Comment by abique** [comment]
ah it was the rebase and merge the problem

**Comment by abique** [comment]
But I did merge your other pull request; what does this one bring?

**Comment by renich** [comment]
The removal of the unnecessary dbus thing related to Vital.

**Comment by abique** [comment]
I close this pull request as the master is already on 3.3.5.

**Pull request closed without merging**
